[package]
name = "chess-kit"
version = "0.1.0"
edition = "2024"

[dependencies]
chess-kit-derive = { path = "chess-kit-derive" }

[dependencies.bitflags]
version = "2.10.0"

[dependencies.rand]
version = "0.9.2"
