[package]
name = "chess-kit-movegen"
version = "0.1.0"
edition = "2024"

[dependencies]
chess-kit-attack-table = { path = "../attack_table" }
chess-kit-position = { path = "../position" }
chess-kit-primitives = { path = "../primitives" }
